### ISSUE TITLE
Getting the Estimated ET_f for a Given Region

### ISSUE THREAD

**Issue by CarlyLarsson** [Open-ET/openet-ssebop#6]
In all the examples and documentation in the Readme, there is no explanation of how to get the actual value of the final ET from the model over the given region. In the 'properties' of an ssebop_obj it gives you the TCORR, which is explained in the Readme as "model uses a correction coefficient (C-factor) uniquely calculated for each Landsat scene from well-watered/vegetated pixels. This temperature correction component is based on a ratio of Tmax and Land Surface Temperature (LST) that has passed through several conditions such as NDVI limits."
Is the calculated ET stored back into this field, or is there another way to get either the total ET over the region or the average?

**Comment by cgmorton** [comment]
One quick warning is that this model is still in "Beta", results and values will probably change, and it should not be used for any real analysis (yet).  Also, the primary purpose of this implementation of SSEBop is to generate Earth Engine ETf images that a user could then use for further analysis in Earth Engine (like computing area averages using reduceRegion calls).   

That being said, we definitely should include some examples showing how to do this further analysis.  Can you provide a little more background or details about what you are trying to do?  It would help us in putting together a useful example.

**Comment by CarlyLarsson** [comment]
I'm a Masters student at UCSB, working in RACELab (http://www.cs.ucsb.edu/~ckrintz/racelab.html). A subset of people in our lab are working on a project called Smart Farm. Right now we are interested in different models for estimating Evapotranspiration, specifically looking at methods that would be easy for farmers to use in California. When I was looking into SSEBOP, I found the OpenET page and this API. 
I know in theory it is possible to use CIMIS weather station data and Landsat data of California to implement SSEBOP, but when I saw this API I thought it would be better to utilize existing tools (in beta I know) than try to reinvent the wheel. 
I would be curious to know how you are measuring the accuracy of the API's output (you could try and compare output to UC Davis's Lysimeter, but you might already be doing something similar)? I'm attaching a Jupyter Notebook where I've been trying to adapt your examples to Santa Barbara county. 
I also noticed one of the examples "API Call Example" doesn't work. I've had quite a few roadblocks to my understanding as I've never used Landsat data before, or the Python API for the Google Earth Engine. 
You might also want to put in the README the recommended environment for running this API. Google Earth Engine Instructions for setting up things in a Docker Container didn't seem compatible when I tried it. I ended up installing everything to my local machine, but maybe there is a way more in line with EE instructions that I don't know about.
