### ISSUE TITLE
Fix ET "Blooming" Around water bodies

### ISSUE THREAD

**Issue by gabe-parrish** [Open-ET/openet-ssebop#62]
Around water bodies, especially in deserts. We notice a halo of high ET around the entire water body. Gabriel Senay found a fix, which essentially amounts to commenting out this line:
https://github.com/Open-ET/openet-ssebop/blob/fe974e58ee8da109c41b8fc6a8c965baccea8173/openet/ssebop/image.py#L894

###Blooming Example
![bloomed_ET](https://github.com/Open-ET/openet-ssebop/assets/21353922/74184076-4b4c-4c66-bdf1-c30a33f4702a)

### Fixed ET:
![fixed_ET](https://github.com/Open-ET/openet-ssebop/assets/21353922/331601dc-68ed-4bf8-a47f-7b14ebe1d9d8)

**Comment by macfriedrichs** [comment]
One preferred solution to review - Replacing lst_smooth_unmasked with Tc_warm100 derivative for the last Tc_cold layer condition as follows:

`var Tc_cold = lst_smooth_unmasked
        .where((ndvi_smooth.gte(0).and(ndvi_smooth.lte(ndvi_threshold))), Tc_warm)
        .where(ndvi_smooth.gt(ndvi_threshold), lst_smooth)
        .where(wet_region_mask_5km, Tc_warm100)
        .where(ndvi_smooth_unmasked.lt(0), lst_smooth_unmasked)

with

`var Tc_cold = lst_smooth_unmasked
        .where((ndvi_smooth.gte(0).and(ndvi_smooth.lte(ndvi_threshold))), Tc_warm) 
        .where(ndvi_smooth.gt(ndvi_threshold), lst_smooth)
        .where(wet_region_mask_5km, Tc_warm100)
        .where(ndvi_smooth_unmasked.lt(0), Tc_warm100)
