### ISSUE TITLE
Add support for setting a custom LST source image collection in from_landsat_c2_sr() and from_image_id() methods

### ISSUE THREAD

**Issue by cgmorton** [Open-ET/openet-ssebop#64]
This parameter will be used to set the collection ID for an image collection of sharpened and/or realtime LST images that could be used instead of the default LST band.

The easiest thing is to structure this parameter somewhat similar to the c2_lst_correct flag that is being parsed inside `.from_landsat_c2_sr()`.  The parameter will need to be popped out of the kwargs before instantiating the class (again similar to c2_lst_correct).  

Let's call it "lst_source" for now to match the naming in DisALEXI, but this could change later on.

**Comment by gabe-parrish** [comment]
@cgmorton I made some commits. Which i tested in the notebook (also named lst_source.py). ETf can be calculated, etc, but I feel like I am not setting properties fully. Plus I think I left some begavior in .from_landsat_c2_sr() that you had wanted transfered to the lst() lazy property. But It's a first cut. Will you take a look?
